### ISSUE TITLE
Fix error output when email and password are incorrect and project Id was not passed for issues.

### ISSUE THREAD

**Issue by Bracciata** [dequelabs/monitor-utility#23]
The following should report an authentication issue. We should potentially move the authentication test to one function related to index.js

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/13560664/235933180-3439db22-75f3-4272-b22e-39f242d1b0ab.png">

**Comment by JaiRai0304** [comment]
We no longer displY THIS PROMPT. It seems its an outdated feature request.
