### ISSUE TITLE
Map weight numbers to the severity Impact text (Elevance Health Request)

### ISSUE THREAD

**Issue by WestonCagle** [dequelabs/monitor-utility#44]
**Describe the solution you'd like**
Customer requested that the issues output contain the impact label available in axe Monitor (Critical, Serious, Moderate, Minor) rather than the API weightage (3, 2, 1, 0).

**Comment by JaiRai0304** [comment]
Closing the issue as the feature is developed and merged into the main branch.
PR https://github.com/dequelabs/monitor-utility/pull/45
