### ISSUE TITLE
Unable to run project.

### ISSUE THREAD

**Issue by YuriiNadala1** [dequelabs/monitor-utility#46]
**Describe the bug**
Hi when I try to run an app i got errors
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN
npm ERR! errno SELF_SIGNED_CERT_IN_CHAIN
npm ERR! request to https://agora.dequecloud.com/artifactory/api/npm/dequelabs/yocto-queue/-/yocto-queue-0.1.0.tgz failed, reason: self-signed certificate in certificate chain

Looks like I need a special account to access certain content via this API, can you support me?

**Comment by JaiRai0304** [comment]
This is something related to your organization firewall which is blocking the downloading of dependent node packages of this application.

Hence , closing this issue.
