### ISSUE TITLE
Add Project ID Column in Monitor Utility Output

### ISSUE THREAD

**Issue by WestonCagle** [dequelabs/monitor-utility#52]
**Is your feature request related to a problem? Please describe.**
It is very difficult to isolate the project ID for each project. This project ID is leveraged when trying to pull issue specific data for projects using the Monitor Utility but there is no current way to pull project ID for a bulk amount of projects. 
**Describe the solution you'd like**
The project pull via the Monitor Utility should include a column that contains each project's project ID number. It currently exists in the report but the number is within the share report link which makes this difficult to copy a list of IDs at one time. 
**Describe alternatives you've considered**
n/a
**Additional context**
n/a

**Comment by JaiRai0304** [comment]
Hi @WestonCagle - Its done. Please take a latest pull of the code.
